name: Central Mirror

on:
  repository_dispatch:
    types: [mirror_trigger]
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Run mirror script
        env:
          GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
        run: bash mirror.sh
